### ISSUE TITLE
SELECT command denied to user 'orchestrator'@'172.22.0.3' for table 'qos_reservation'

### ISSUE THREAD

**Issue by holgerbrandl** [eclipse-arrowhead/core-java-spring#272]
I've tried to follow the docker-all setup instuctions. The system appears to startup correctly. However, after the initial internal setup it starts emitting errors related to SQl permissions:
```
arrowhead_core          | 2020-10-23 05:11:21.190  WARN 52a2b2af3391 --- [eduler_Worker-1] o.h.e.j.s.SqlExceptionHelper             : SQL Error: 1142, SQLState: 42000
arrowhead_core          | 2020-10-23 05:11:21.190 ERROR 52a2b2af3391 --- [eduler_Worker-1] o.h.e.j.s.SqlExceptionHelper             : SELECT command denied to user 'orchestrator'@'172.22.0.3' for table 'qos_reservation'
arrowhead_core          | 2020-10-23 05:11:21.192 ERROR 52a2b2af3391 --- [eduler_Worker-1] o.q.c.JobRunShell                        : Job DEFAULT.Services_Reservation_Check_Task_Detail threw an unhandled Exception:
arrowhead_core          | eu.arrowhead.common.exception.ArrowheadException: Database operation exception
arrowhead_core          |       at eu.arrowhead.core.qos.database.service.QoSReservationDBService.releaseObsoleteReservations(QoSReservationDBService.java:72)
arrowhead_core          |       at eu.arrowhead.core.qos.database.service.QoSReservationDBService$$FastClassBySpringCGLIB$$1c5432f9.invoke(<generated>)
arrowhead_core          |       at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
arrowhead_core          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
arrowhead_core          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
arrowhead_core          |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
arrowhead_core          |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
arrowhead_core          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
arrowhead_core          |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
arrowhead_core          |       at eu.arrowhead.core.qos.database.service.QoSReservationDBService$$EnhancerBySpringCGLIB$$4351330b.releaseObsoleteReservations(<generated>)
arrowhead_core          |       at eu.arrowhead.core.qos.quartz.task.ReservationCheckTask.execute(ReservationCheckTask.java:48)
arrowhead_core          |       at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
arrowhead_core          |       at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
arrowhead_core          | 2020-10-23 05:11:21.192 ERROR 52a2b2af3391 --- [eduler_Worker-1] o.q.c.ErrorLogger                        : Job (DEFAULT.Services_Reservation_Check_Task_Detail threw an exception.
```

Did I miss a step during the preparation of my deployment or this the intended behavior?

**Comment by tsvetlin** [comment]
Hello!

The issue is, the SQL file in docker-all uses an older database file:
https://github.com/arrowhead-f/core-java-spring/blob/master/docker-all/example/sql/setup.sql 
And is missing the QoS Manager Related entries:
https://github.com/arrowhead-f/core-java-spring/blob/master/scripts/orchestrator_privileges.sql

You can update that file by copying there the missing lines and rerun the docker-all.

**Comment by holgerbrandl** [comment]
Will this be fixed in the repo?
