### ISSUE TITLE
 The driver has not received any packets from the server

### ISSUE THREAD

**Issue by pkrasnousov** [eclipse-arrowhead/core-java-spring#325]
I am trying to run **docker-all** variant in test env. 
After all preparations(wget sql files, create docker volume, create target dir with JARs) I run  **docker-compose up --build** and get next error:

```arrowhead_core          | 2021-07-07 14:44:29.189 ERROR b9a35871eae7 --- [           main] c.z.h.p.HikariPool                       : HikariPool-3 - Exception during pool initialization.
arrowhead_core          | com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
arrowhead_core          |
arrowhead_core          | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
arrowhead_core          |       at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
arrowhead_core          |       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
arrowhead_core          |       at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
arrowhead_core          |       at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
arrowhead_core          |       at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
arrowhead_core          |       at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
arrowhead_core          |       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
arrowhead_core          |       at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
arrowhead_core          |       at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
arrowhead_core          |       at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
arrowhead_core          |       at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
arrowhead_core          |       at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
arrowhead_core          |       at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
arrowhead_core          |       at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
arrowhead_core          |       at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
arrowhead_core          |       at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
arrowhead_core          |       at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:323)
arrowhead_core          |       at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:123)
arrowhead_core          |       at org.springframework.boot.jdbc.AbstractDataSourceInitializer.isEnabled(AbstractDataSourceInitializer.java:74)
arrowhead_core          |       at org.springframework.boot.jdbc.AbstractDataSourceInitializer.initialize(AbstractDataSourceInitializer.java:54)
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
arrowhead_core          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
arrowhead_core          |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
arrowhead_core          |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
arrowhead_core          |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
arrowhead_core          |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
arrowhead_core          |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:452)
arrowhead_core          |       at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:526)
arrowhead_core          |       at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496)
arrowhead_core          |       at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:636)
arrowhead_core          |       at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:180)
arrowhead_core          |       at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
arrowhead_core          |       at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
arrowhead_core          |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
arrowhead_core          |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
arrowhead_core          |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
arrowhead_core          |       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
arrowhead_core          |       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
arrowhead_core          |       at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
arrowhead_core          |       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
arrowhead_core          |       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
arrowhead_core          |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
arrowhead_core          |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
arrowhead_core          |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
arrowhead_core          |       at eu.arrowhead.core.serviceregistry.ServiceRegistryMain.main(ServiceRegistryMain.java:40)
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
arrowhead_core          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
arrowhead_core          |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
arrowhead_core          |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
arrowhead_core          |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
arrowhead_core          |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
arrowhead_core          |       at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
arrowhead_core          | Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
arrowhead_core          |
arrowhead_core          | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
arrowhead_core          |       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
arrowhead_core          |       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
arrowhead_core          |       at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
arrowhead_core          |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
arrowhead_core          |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
arrowhead_core          |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
arrowhead_core          |       at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
arrowhead_core          |       at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
arrowhead_core          |       at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
arrowhead_core          |       at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
arrowhead_core          |       at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
arrowhead_core          |       ... 66 more
arrowhead_core          | Caused by: java.net.ConnectException: Connection refused (Connection refused)
arrowhead_core          |       at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
arrowhead_core          |       at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
arrowhead_core          |       at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
arrowhead_core          |       at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
arrowhead_core          |       at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
arrowhead_core          |       at java.base/java.net.Socket.connect(Unknown Source)
arrowhead_core          |       at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
arrowhead_core          |       at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
arrowhead_core          |       ... 69 more
arrowhead_core          | 2021-07-07 14:44:29.241  INFO b9a35871eae7 --- [           main] e.a.c.q.u.UriCrawlerTaskConfig           : URI Crawler task scheduled.
arrowhead_core          | 2021-07-07 14:44:29,244 Log4j2-TF-5-AsyncLoggerConfig-4 ERROR Unable to write to database [JdbcManager{name=MySQLDatabase, bufferSize=0, tableName=logs, columnConfigs=[{ name=log_id, layout=%u, literal=null, timestamp=false }, { name=entry_date, layout=null, literal=null, timestamp=true }, { name=logger, layout=%logger, literal=null, timestamp=false }, { name=log_level, layout=%level, literal=null, timestamp=false }, { name=message, layout=%m, literal=null, timestamp=false }, { name=exception, layout=%throwable , literal=null, timestamp=false }], columnMappings=[]}] for appender [MySQLDatabase]. org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to JDBC Manager 'JdbcManager{name=MySQLDatabase, bufferSize=0, tableName=logs, columnConfigs=[{ name=log_id, layout=%u, literal=null, timestamp=false }, { name=entry_date, layout=null, literal=null, timestamp=true }, { name=logger, layout=%logger, literal=null, timestamp=false }, { name=log_level, layout=%level, literal=null, timestamp=false }, { name=message, layout=%m, literal=null, timestamp=false }, { name=exception, layout=%throwable , literal=null, timestamp=false }], columnMappings=[]}': JDBC connection not available.
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.checkConnection(JdbcDatabaseManager.java:488)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.connectAndStart(JdbcDatabaseManager.java:585)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.writeThrough(JdbcDatabaseManager.java:813)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.AbstractDatabaseManager.write(AbstractDatabaseManager.java:264)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.AbstractDatabaseAppender.append(AbstractDatabaseAppender.java:110)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.callAppenders(AsyncLoggerConfig.java:127)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.log(AsyncLoggerConfig.java:121)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.logToAsyncLoggerConfigsOnCurrentThread(AsyncLoggerConfig.java:169)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:111)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:97)
arrowhead_core          |       at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
arrowhead_core          |       at java.base/java.lang.Thread.run(Unknown Source)
arrowhead_core          |
arrowhead_core          | 2021-07-07 14:44:29,245 Log4j2-TF-5-AsyncLoggerConfig-4 ERROR An exception occurred processing Appender MySQLDatabase org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to JDBC Manager 'JdbcManager{name=MySQLDatabase, bufferSize=0, tableName=logs, columnConfigs=[{ name=log_id, layout=%u, literal=null, timestamp=false }, { name=entry_date, layout=null, literal=null, timestamp=true }, { name=logger, layout=%logger, literal=null, timestamp=false }, { name=log_level, layout=%level, literal=null, timestamp=false }, { name=message, layout=%m, literal=null, timestamp=false }, { name=exception, layout=%throwable , literal=null, timestamp=false }], columnMappings=[]}': JDBC connection not available.
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.checkConnection(JdbcDatabaseManager.java:488)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.connectAndStart(JdbcDatabaseManager.java:585)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.jdbc.JdbcDatabaseManager.writeThrough(JdbcDatabaseManager.java:813)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.AbstractDatabaseManager.write(AbstractDatabaseManager.java:264)
arrowhead_core          |       at org.apache.logging.log4j.core.appender.db.AbstractDatabaseAppender.append(AbstractDatabaseAppender.java:110)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
arrowhead_core          |       at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.callAppenders(AsyncLoggerConfig.java:127)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
arrowhead_core          |       at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.log(AsyncLoggerConfig.java:121)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfig.logToAsyncLoggerConfigsOnCurrentThread(AsyncLoggerConfig.java:169)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:111)
arrowhead_core          |       at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:97)
arrowhead_core          |       at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
arrowhead_core          |       at java.base/java.lang.Thread.run(Unknown Source)
arrowhead_core          |
arrowhead_core          | 2021-07-07 14:44:29.799  WARN b9a35871eae7 --- [           main] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
```

From the test container in the same network as ` arrowhead_core_mysql` container I can connect to mysql host using credentials from .properties file
```
root@5eed3f7eea62:/# mysql -u service_registry -p -h arrowhead_core_mysql
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.34 MySQL Community Server (GPL)

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| arrowhead          |
+--------------------+
2 rows in set (0.00 sec)

```

JAR release 4.3.0

Any ideas?

**Comment by tsvetlin** [comment]
Hello!

This issue was solved in #312 The application properties should be updated. If you have any more questions, or need help, feel free to reply to this issue.

Best wishes,
Svetlin
