### ISSUE TITLE
"The system is not part of the same certificate chain of trust"

### ISSUE THREAD

**Issue by yustiks** [eclipse-arrowhead/core-java-spring#456]
I try to follow an example with Arrowhead Demo Car, and I can not re-produce the steps given in the video instructions.
I would like to understand what is the problem here which I have.
After I run the command:
```
java -jar .\demo-car-provider-4.4.0.2.jar
```
I have the following error:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.2)

2024-03-29 12:08:19.073  INFO 12676 --- [           main] a.a.d.c.CarProviderMain                  : Starting CarProviderMain v4.4.0.2 using Java 11.0.22 on DESKTOP-5N88CTJ with PID 12676 (C:\Users\aa\Downloads\application-example_v4.4.0.2-executable\demo-car\demo-car-provider\demo-car-provider-4.4.0.2.jar started by aa in C:\Users\aa\Downloads\application-example_v4.4.0.2-executable\demo-car\demo-car-provider)
2024-03-29 12:08:19.089  INFO 12676 --- [           main] a.a.d.c.CarProviderMain                  : No active profile set, falling back to default profiles: default
2024-03-29 12:08:20.000  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : ####################################################################################
2024-03-29 12:08:20.000  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : #
2024-03-29 12:08:20.000  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # TomcatCustomizer
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : #
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # custom maxKeepAliveRequests 1
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # origin keepalive timeout: 60000 ms
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # keepalive timeout: 60000 ms
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # connection timeout: 60000 ms
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : # max connections: 8192
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : #
2024-03-29 12:08:20.015  INFO 12676 --- [           main] e.a.a.s.p.c.ContainerConfiguration       : ####################################################################################
2024-03-29 12:08:20.038  INFO 12676 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat initialized with port(s): 8888 (https)
2024-03-29 12:08:20.047  INFO 12676 --- [           main] o.a.c.c.StandardService                  : Starting service [Tomcat]
2024-03-29 12:08:20.047  INFO 12676 --- [           main] o.a.c.c.StandardEngine                   : Starting Servlet engine: [Apache Tomcat/9.0.56]
2024-03-29 12:08:20.094  INFO 12676 --- [           main] o.a.c.c.C.[.[.[/]                        : Initializing Spring embedded WebApplicationContext
2024-03-29 12:08:20.094  INFO 12676 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 974 ms
2024-03-29 12:08:20.454  INFO 12676 --- [           main] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 69a74cf2-2678-49f9-bde6-122430c32245

2024-03-29 12:08:20.501  INFO 12676 --- [           main] e.a.c.f.ArrowheadFilter                  : ProviderTokenSecurityFilter is active
2024-03-29 12:08:20.517  INFO 12676 --- [           main] o.s.s.w.a.c.ChannelProcessingFilter      : Validated configuration attributes
2024-03-29 12:08:20.517  INFO 12676 --- [           main] o.s.s.w.DefaultSecurityFilterChain       : Will secure any request with [org.springframework.security.web.access.channel.ChannelProcessingFilter@4c9e38, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@5f14a673, org.springframework.security.web.context.SecurityContextPersistenceFilter@16c3ca31, org.springframework.security.web.header.HeaderWriterFilter@53dfacba, org.springframework.security.web.authentication.logout.LogoutFilter@1473b8c0, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@2d6aca33, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@35f8a9d3, eu.arrowhead.application.skeleton.provider.security.ProviderTokenSecurityFilter@726a17c4, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5dc3fcb7, org.springframework.security.web.session.SessionManagementFilter@1e63d216, org.springframework.security.web.access.ExceptionTranslationFilter@6a4d7f76]
2024-03-29 12:08:20.863  INFO 12676 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat started on port(s): 8888 (https) with context path ''
2024-03-29 12:08:20.863  INFO 12676 --- [           main] a.a.a.a.l.c.ApplicationInitListener      : Security mode: SECURED
2024-03-29 12:08:20.889  INFO 12676 --- [           main] a.a.a.a.l.c.ApplicationInitListener      : Application system CN: cardemoprovider.testcloud2.aitia.arrowhead.eu
2024-03-29 12:08:20.972 ERROR 12676 --- [           main] e.a.c.h.HttpService                      : The system at https://127.0.0.1:8443/serviceregistry/echo is not part of the same certificate chain of trust!
2024-03-29 12:08:20.972  INFO 12676 --- [           main] a.a.a.a.l.c.ApplicationInitListener      : 'SERVICEREGISTRY' core system is NOT reachable.
2024-03-29 12:08:21.053 ERROR 12676 --- [           main] e.a.c.h.HttpService                      : The system at https://127.0.0.1:8443/serviceregistry/query is not part of the same certificate chain of trust!
2024-03-29 12:08:21.054  INFO 12676 --- [           main] a.a.a.a.l.c.ApplicationInitListener      : 'AUTHORIZATION' core system is NOT reachable.
2024-03-29 12:08:21.058 ERROR 12676 --- [           main] e.a.c.h.HttpService                      : The system at https://127.0.0.1:8443/serviceregistry/query is not part of the same certificate chain of trust!
2024-03-29 12:08:21.066  INFO 12676 --- [           main] o.a.c.c.StandardService                  : Stopping service [Tomcat]
2024-03-29 12:08:21.066  INFO 12676 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-03-29 12:08:21.082 ERROR 12676 --- [           main] o.s.b.SpringApplication                  : Application run failed

eu.arrowhead.common.exception.ArrowheadException: Authorization public key is null
        at eu.arrowhead.application.skeleton.provider.ProviderApplicationInitListener.setTokenSecurityFilter(ProviderApplicationInitListener.java:118) ~[classes!/:4.4.0.2]
        at eu.arrowhead.application.skeleton.provider.ProviderApplicationInitListener.customInit(ProviderApplicationInitListener.java:80) ~[classes!/:4.4.0.2]
        at ai.aitia.arrowhead.application.library.config.ApplicationInitListener.onApplicationEvent(ApplicationInitListener.java:74) ~[arrowhead-application-library-java-spring-4.4.0.2.jar!/:4.4.0.2]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.14.jar!/:5.3.14]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.2.jar!/:2.6.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) [spring-boot-2.6.2.jar!/:2.6.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) [spring-boot-2.6.2.jar!/:2.6.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.2.jar!/:2.6.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.2.jar!/:2.6.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) [spring-boot-2.6.2.jar!/:2.6.2]
        at ai.aitia.demo.car_provider.CarProviderMain.main(CarProviderMain.java:18) [classes!/:4.4.0.2]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [demo-car-provider-4.4.0.2.jar:4.4.0.2]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [demo-car-provider-4.4.0.2.jar:4.4.0.2]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [demo-car-provider-4.4.0.2.jar:4.4.0.2]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [demo-car-provider-4.4.0.2.jar:4.4.0.2]

2024-03-29 12:08:21.098 ERROR 12676 --- [           main] e.a.c.h.HttpService                      : The system at https://127.0.0.1:8443/serviceregistry/unregister?system_name=cardemoprovider&address=127.0.0.1&port=8888&service_definition=create-car&service_uri=/car is not part of the same certificate chain of trust!
2024-03-29 12:08:21.098  WARN 12676 --- [           main] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'providerApplicationInitListener' threw an exception: eu.arrowhead.common.exception.AuthException: The system at https://127.0.0.1:8443/serviceregistry/unregister?system_name=cardemoprovider&address=127.0.0.1&port=8888&service_definition=create-car&service_uri=/car is not part of the same certificate chain of trust!
```

What is the problem?
Any thoughts on this?

**Comment by jenseliasson** [comment]
Hi.
Looks like a certificate chain problem. Did you generate the proper
certificates?

Jens

**Comment by yustiks** [comment]
@jenseliasson  the certificate was generated according to the instructions. 
I use the same as they adviced (sysop if I remember correctly)

**Comment by borditamas** [comment]
support continues on another channel
