### ISSUE TITLE
Gatekeeper Gatekeeper Tests fail

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#67]
Hello

I wanted to check today if the problem with ticket #59  was solved, but a new error occurred. As soon as I try to compile the project using the `mvn clean install` command, Maven aborts the gatekeeper tests. Logs are attached as well. If I skip the tests, I don't get access to the web interfaces. In the process overview all processes are running, but they don't create a CPU load. Normally I get almost a full CPU load for the first few minutes when starting the services.

Greetings
BlackRose01

[gatekeeper.zip](https://github.com/arrowhead-f/core-java-spring/files/3620869/gatekeeper.zip)

**Comment by tsvetlin** [comment]
I can confirm the issue. CI/CD build fails because of that.
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.5.RELEASE)

2019-09-17 10:10:24.739  INFO d122b5edf859 --- [           main] e.a.c.g.s.GatewayAccessControlFilterTest : Starting GatewayAccessControlFilterTest on d122b5edf859 with PID 1117 (started by root in /core-java-spring/gateway)
2019-09-17 10:10:24.750  INFO d122b5edf859 --- [           main] e.a.c.g.s.GatewayAccessControlFilterTest : No active profile set, falling back to default profiles: default
2019-09-17 10:10:26.955  INFO d122b5edf859 --- [           main] e.a.c.f.ArrowheadFilter                  : GatewayAccessControlFilter is active
2019-09-17 10:10:27.121  INFO d122b5edf859 --- [           main] e.a.c.q.u.UriCrawlerTaskConfig           : URI Crawler task scheduled.
2019-09-17 10:10:27.299  WARN d122b5edf859 --- [           main] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2019-09-17 10:10:27.696  INFO d122b5edf859 --- [           main] e.a.c.f.ArrowheadFilter                  : PayloadSizeFilter is active
2019-09-17 10:10:28.434  INFO d122b5edf859 --- [           main] e.a.c.t.StandaloneModeInTests            : STANDALONE mode is set...
2019-09-17 10:10:28.436  INFO d122b5edf859 --- [           main] e.a.c.ApplicationInitListener            : Core system name: GATEWAY
2019-09-17 10:10:28.437  INFO d122b5edf859 --- [           main] e.a.c.ApplicationInitListener            : Server mode: SECURED
2019-09-17 10:10:28.546  INFO d122b5edf859 --- [           main] e.a.c.ApplicationInitListener            : Server CN: gateway.testcloud2.aitia.arrowhead.eu
2019-09-17 10:10:28.641  INFO d122b5edf859 --- [           main] e.a.c.g.s.GatewayAccessControlFilterTest : Started GatewayAccessControlFilterTest in 3.941 seconds (JVM running for 47.517)
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.203 s - in eu.arrowhead.core.gateway.security.GatewayAccessControlFilterTest
[INFO] Running eu.arrowhead.core.gateway.thread.ConsumerSideServerSocketThreadTest
2019-09-17 10:10:29.299 ERROR d122b5edf859 --- [           main] e.a.c.g.t.SSLContextFactory              : SSL context creation failed: invalid not found
[ERROR] Tests run: 21, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.483 s <<< FAILURE! - in eu.arrowhead.core.gateway.thread.ConsumerSideServerSocketThreadTest
[ERROR] testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(eu.arrowhead.core.gateway.thread.ConsumerSideServerSocketThreadTest)  Time elapsed: 0.373 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at eu.arrowhead.core.gateway.thread.ConsumerSideServerSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(ConsumerSideServerSocketThreadTest.java:249)

[INFO] Running eu.arrowhead.core.gateway.thread.SSLContextFactoryTest
2019-09-17 10:10:29.651 ERROR d122b5edf859 --- [           main] e.a.c.g.t.SSLContextFactory              : SSL context creation failed: invalid not found
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.288 s - in eu.arrowhead.core.gateway.thread.SSLContextFactoryTest
[INFO] Running eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest
2019-09-17 10:10:30.095 ERROR d122b5edf859 --- [           main] e.a.c.g.t.SSLContextFactory              : SSL context creation failed: invalid not found
[ERROR] Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.447 s <<< FAILURE! - in eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest
[ERROR] testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest)  Time elapsed: 0.333 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
relayClient.sendBytes(
    <any javax.jms.Session>,
    <any javax.jms.MessageProducer>,
    <any java.security.PublicKey>,
    <any byte[]>
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(ProviderSideSocketThreadTest.java:388)

However, there were exactly 2 interactions with this mock:
relayClient.isConnectionClosed(
    eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest$2@26ffe94e
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThread.<init>(ProviderSideSocketThread.java:70)

relayClient.closeConnection(
    eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest$2@26ffe94e
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThread.close(ProviderSideSocketThread.java:222)


	at eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(ProviderSideSocketThreadTest.java:388)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ProviderSideSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes:388 
Wanted but not invoked:
relayClient.sendBytes(
    <any javax.jms.Session>,
    <any javax.jms.MessageProducer>,
    <any java.security.PublicKey>,
    <any byte[]>
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes(ProviderSideSocketThreadTest.java:388)

However, there were exactly 2 interactions with this mock:
relayClient.isConnectionClosed(
    eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest$2@26ffe94e
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThread.<init>(ProviderSideSocketThread.java:70)

relayClient.closeConnection(
    eu.arrowhead.core.gateway.thread.ProviderSideSocketThreadTest$2@26ffe94e
);
-> at eu.arrowhead.core.gateway.thread.ProviderSideSocketThread.close(ProviderSideSocketThread.java:222)


[ERROR] Errors: 
[ERROR]   ConsumerSideServerSocketThreadTest.testRunWhenOtherSideCloseTheConnectionAfterSendingSomeBytes:249 » Connect
[INFO] 
[ERROR] Tests run: 290, Failures: 1, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for core-java-spring 4.1.3:
[INFO] 
[INFO] core-java-spring ................................... SUCCESS [  2.054 s]
[INFO] Core Common ........................................ SUCCESS [ 28.924 s]
[INFO] Arrowhead Service Registry ......................... SUCCESS [ 51.603 s]
[INFO] Arrowhead Authorization ............................ SUCCESS [ 50.535 s]
[INFO] Arrowhead Orchestrator ............................. SUCCESS [ 38.811 s]
[INFO] Arrowhead Event Handler ............................ SUCCESS [  0.948 s]
[INFO] Arrowhead Gatekeeper ............................... SUCCESS [01:00 min]
[INFO] Arrowhead Gateway .................................. FAILURE [ 52.282 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:46 min
[INFO] Finished at: 2019-09-17T10:10:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project arrowhead-gateway: There are test failures.
[ERROR] 
[ERROR] Please refer to /core-java-spring/gateway/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :arrowhead-gateway
```

**Comment by rbocsi** [comment]
Hi,

The tests failed because gatekeeper only works in secured mode (the communication via relays made neccessary that). Of course, the gatekeeper does not start in insecure mode, so you can't access its web interface.

**Comment by rbocsi** [comment]
Szvetlin,

This is different issue. As you can see, the gatekeeper tests runs fine in your case, gateway fails.

**Comment by BlackRose01** [comment]
@rbocsi Ah ok. But are there workarounds for this problem? Because the problem with me goes so far that all web interfaces of each module are not attainable.

**Comment by rbocsi** [comment]
@BlackRose01 I tried to reproduce the issue in my computer. I switched to master and set server.ssl.enabled=false in every core system, then mvn clean install -DskipTests=true. After that I start the systems (gatekeeper failed to start of course). After that I can access the web interface of SR, Auth and Orchestrator successfully. 

So I don't understand what is the problem in your case. Can you send me the application.properties files? It's in the target subfolder of each core system's folder besides the jar file.

**Comment by BlackRose01** [comment]
@rbocsi There you have.

[Properties.zip](https://github.com/arrowhead-f/core-java-spring/files/3621329/Properties.zip)

**Comment by BlackRose01** [comment]
So. When I skip the tests at the beginning it starts now on my localhost. But not on the server. So I will talk with the firewall expert. Maybe there is a misconfiguration in the config.

**Comment by BlackRose01** [comment]
@tsvetlin @rbocsi noted that the gatekeeper only works when the core service is not running in Insecure mode. Maybe you can add a check to the tests that will skip it if Insecure mode is enabled.

**Comment by BlackRose01** [comment]
Ok. The Problem is solved. We missed to configure the Arrowhead communication to other clients. But thank you for your help.
